// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADk5nY6Bnxh0hbAAhvSnM0tIFS5h16cdI',
    appId: '1:179904000591:web:f4d8e180016de014ed303a',
    messagingSenderId: '179904000591',
    projectId: 'login-8cb26',
    authDomain: 'login-8cb26.firebaseapp.com',
    storageBucket: 'login-8cb26.firebasestorage.app',
    measurementId: 'G-091J46373K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9zJSY_QqiQDpdcj-xBRBQKbBJNqKgH0A',
    appId: '1:179904000591:android:8bd4247cc0eb31aeed303a',
    messagingSenderId: '179904000591',
    projectId: 'login-8cb26',
    storageBucket: 'login-8cb26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbmeMRZbU3Dx37j_VNerjuC5utXFAKPlQ',
    appId: '1:179904000591:ios:4d0a936f5958d694ed303a',
    messagingSenderId: '179904000591',
    projectId: 'login-8cb26',
    storageBucket: 'login-8cb26.firebasestorage.app',
    iosClientId: '179904000591-e4mjul25smqa9t90ip3fllmjnddm3cst.apps.googleusercontent.com',
    iosBundleId: 'com.example.cabinCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbmeMRZbU3Dx37j_VNerjuC5utXFAKPlQ',
    appId: '1:179904000591:ios:4d0a936f5958d694ed303a',
    messagingSenderId: '179904000591',
    projectId: 'login-8cb26',
    storageBucket: 'login-8cb26.firebasestorage.app',
    iosClientId: '179904000591-e4mjul25smqa9t90ip3fllmjnddm3cst.apps.googleusercontent.com',
    iosBundleId: 'com.example.cabinCheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADk5nY6Bnxh0hbAAhvSnM0tIFS5h16cdI',
    appId: '1:179904000591:web:b73522eb7eefd051ed303a',
    messagingSenderId: '179904000591',
    projectId: 'login-8cb26',
    authDomain: 'login-8cb26.firebaseapp.com',
    storageBucket: 'login-8cb26.firebasestorage.app',
    measurementId: 'G-FBD0REWQ3L',
  );

}